// Code generated by "stringer -type=Size -output=size_string.go"; DO NOT EDIT.

package size

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unset-0]
	_ = x[Byte-1]
	_ = x[Word-2]
	_ = x[Longword-3]
}

const _Size_name = "UnsetByteWordLongword"

var _Size_index = [...]uint8{0, 5, 9, 13, 21}

func (i Size) String() string {
	if i < 0 || i >= Size(len(_Size_index)-1) {
		return "Size(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Size_name[_Size_index[i]:_Size_index[i+1]]
}
